### ISSUE TITLE
issue for lesson - Demo of Feecc(en)

### ISSUE THREAD

**Issue by Crzzx** [airalab/robonomics.academy#183]
### Issue description

Не понятно, что на писано две команды которые нужно выполнить последовательно, запустить контейнер "sudo docker exec -ti feecc_academy_hid_emulator sh" и запустить скрипт "python3 hid-emulator.py".
Для более понятной инструкции можно обозначить все новые строки символом $.

### Lesson Page

Launching demo, 002

**Comment by Fingerling42** [comment]
Fixed #184
