### ISSUE TITLE
issue for lesson - 2, At the Intersection of Cybernetics and Economics(en)

### ISSUE THREAD

**Issue by Vourhey** [airalab/robonomics.academy#31]
### Issue description

When filling out the test and reloading the page (in my case it shuts down automatically due to inactivity for some time in the background) answers are not restored. It would be good to cache my already answered questions 

### Lesson Page

Test page in Lesson 1 Course 1

**Comment by positivecrash** [comment]
@vol4tim please implement session storage for tests

**Comment by vol4tim** [comment]
Ready. Can you check.
