### ISSUE TITLE
[Issue]: Wrong Language on Listings for Copy

### ISSUE THREAD

**Issue by Fingerling42** [airalab/robonomics.academy#52]
### Issue description

Some listings have the wrong language. 
![bash-to-yaml](https://user-images.githubusercontent.com/17783902/206826894-fec54c27-552e-4a6c-93d3-ea921692c8a2.png)

### Lesson Page

https://robonomics.academy/en/online-courses/smart-home-course/2-raspberry-pi-setup/
https://robonomics.academy/en/online-courses/smart-home-course/3-mqtt-broker-setup/
https://robonomics.academy/en/online-courses/smart-home-course/4-a-gateway-setup-zigbee2mqtt/

**Comment by positivecrash** [comment]
I suppose this is content editor's work. Do you have trouble in editing this?

**Comment by Fingerling42** [comment]
I tried to change this in the code of page (change tag "bash"), but it is not working.

**Comment by positivecrash** [comment]
Provide please list of required languages, so we could add them in config

**Comment by Fingerling42** [comment]
Languages:
- Bash
- JSON
- Python
- YAML

**Comment by positivecrash** [comment]
done
