### ISSUE TITLE
[Issue]: Black Background in Image

### ISSUE THREAD

**Issue by Fingerling42** [airalab/robonomics.academy#53]
### Issue description

The image have black background on light theme.

![black-img](https://user-images.githubusercontent.com/17783902/206827079-45ea4502-0e78-4a66-a8fc-21e0036b29fe.png)

### Lesson Page

https://robonomics.academy/en/online-courses/smart-home-course/3-mqtt-broker-setup/

**Comment by positivecrash** [comment]
This is your content. Place png with transparent background
