### ISSUE TITLE
[Issue]: Line-by-Line Commands Stick Together When Copying

### ISSUE THREAD

**Issue by Fingerling42** [airalab/robonomics.academy#55]
### Issue description

All commands are copied together where they need to be copied line by line. It is needed either to make possible to copy them line by line, or to remove the button for copying from such listings.

![copy-code](https://user-images.githubusercontent.com/17783902/206827328-cbad1a31-ea59-420e-ae4b-5fd1dd32fd3a.png)

### Lesson Page

https://robonomics.academy/en/online-courses/smart-home-course/2-raspberry-pi-setup/
https://robonomics.academy/en/online-courses/smart-home-course/4-a-gateway-setup-zigbee2mqtt/
https://robonomics.academy/en/online-courses/smart-home-course/4-b-gateway-setup-robonomics-sls-gateway/

**Comment by positivecrash** [comment]
Added possibility to remove copy button
