### ISSUE TITLE
[Issue]: Removing Line Numbering

### ISSUE THREAD

**Issue by Fingerling42** [airalab/robonomics.academy#69]
### Issue description

Please, add the ability to remove line numbering.

![image](https://user-images.githubusercontent.com/17783902/209873245-bf75cd32-202e-4009-b2c6-b9e1f0c49bb8.png)

### Lesson Page

https://robonomics.academy/en/online-courses/smart-home-course/2-raspberry-pi-setup/

**Comment by positivecrash** [comment]
You can remove it now, watch https://github.com/airalab/robonomics.academy#how-to-highlight-code
