### ISSUE TITLE
[Issue]: Cannot Use Markdown in Notes and Warnings

### ISSUE THREAD

**Issue by Fingerling42** [airalab/robonomics.academy#98]
**Examples**:

Bold text:
![Screenshot from 2023-03-30 00-34-30](https://user-images.githubusercontent.com/17783902/228682395-cda60b46-d683-4432-93bf-3c9404d95b19.png)

Link:
![Screenshot from 2023-03-30 01-23-50](https://user-images.githubusercontent.com/17783902/228682435-66681cd7-c550-4aaf-9afb-2f33b51c5c3d.png)

**Comment by zirreal** [comment]
Could you try use spaces inside component?  And see if it works.

Example:
<img width="430" alt="1" src="https://user-images.githubusercontent.com/72923911/229044230-d126718e-cf4b-4498-8290-52ff7dffaa04.png">
